CREATE TABLE IF NOT EXISTS cheevohaus.registeredUsers
(
	id	INT NOT NULL AUTO_INCREMENT,
	username	VARCHAR(32) NOT NULL,
	password 	VARCHAR(64) NOT NULL,
	joinedOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(id)
);
